version: 1.0.{build}

install:
# Setup Inno so we can compile the installer
- choco install -y InnoSetup
- set PATH="C:\Program Files (x86)\Inno Setup 5"

build_script:
  - echo "Starting Build script..."
  - nuget restore
  - msbuild /m /p:Configuraiton=Release NZBDash.sln
  
  # Compile installer
  - iscc NZBDash.iss 
  - dir 
  - dir C:\projects\Installer
  - appveyor PushArtifact C:\projects\Installer\setup.exe
