//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZBDash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MockData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NZBDash.Resources.MockData", typeof(MockData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;movies&quot;: [{&quot;status&quot;: &quot;done&quot;, &quot;info&quot;: {&quot;rating&quot;: {&quot;imdb&quot;: [7.6, 261894]}, &quot;genres&quot;: [&quot;Adventure&quot;, &quot;Drama&quot;, &quot;Thriller&quot;, &quot;Biography&quot;], &quot;tmdb_id&quot;: 44115, &quot;plot&quot;: &quot;127 Hours is the true story of mountain climber Aron Ralston&apos;s remarkable adventure to save himself after a fallen boulder crashes on his arm and traps him in an isolated canyon in Utah. Over the next five days Ralston examines his life and survives the elements to finally discover he has the courage and the wherewithal to extricate himself by any m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CouchPotato_MediaList {
            get {
                return ResourceManager.GetString("CouchPotato_MediaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;total_size&quot;: &quot;40.30 GB&quot;,    
        ///    &quot;month_size&quot;: &quot;20.23 GB&quot;,  
        ///    &quot;week_size&quot;: &quot;5.12 GB&quot;, 
        ///    &quot;cache_limit&quot;:&quot;-1&quot;,
        ///    &quot;paused&quot;:true,
        ///    &quot;new_rel_url&quot;:&quot;&quot;,
        ///    &quot;restart_req&quot;:false,
        ///    &quot;slots&quot;:[
        ///    {
        ///        &quot;action_line&quot;:&quot;&quot;,
        ///        &quot;show_details&quot;:&quot;True&quot;,
        ///        &quot;script_log&quot;:&quot;&quot;,
        ///        &quot;meta&quot;:null,
        ///        &quot;fail_message&quot;:&quot;&quot;,
        ///        &quot;loaded&quot;:false,
        ///        &quot;id&quot;:605,
        ///        &quot;size&quot;:&quot;778.1 MB&quot;,
        ///        &quot;category&quot;:&quot;Apps&quot;,
        ///        &quot;pp&quot;:&quot;D&quot;,
        ///        &quot;completeness&quot;:0,
        ///        &quot;scrip [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sabnzbd_History {
            get {
                return ResourceManager.GetString("Sabnzbd_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;timeleft&quot;:&quot;0:00:00&quot;,
        ///    &quot;mb&quot;:854.697841,
        ///    &quot;noofslots&quot;:1,
        ///    &quot;paused&quot;:false,
        ///    &quot;mbleft&quot;:200,
        ///    &quot;diskspace2&quot;:21.980682,
        ///    &quot;diskspace1&quot;:21.980682,
        ///    &quot;kbpersec&quot;:0.000000,
        ///    &quot;jobs&quot;:[
        ///        {&quot;msgid&quot;:&quot;3066202&quot;,
        ///        &quot;filename&quot;:
        ///        &quot;Ubuntu 8.04 (Hardy Heron) - Desktop CD x64&quot;,
        ///        &quot;mbleft&quot;:854.697841,&quot;id&quot;:&quot;SABnzbd_nzo_zt2syz&quot;,
        ///        &quot;mb&quot;:854.697841}
        ///    ]
        ///}.
        /// </summary>
        public static string Sabnzbd_Queue {
            get {
                return ResourceManager.GetString("Sabnzbd_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;seriesId&quot;: 1,
        ///    &quot;episodeFileId&quot;: 0,
        ///    &quot;seasonNumber&quot;: 0,
        ///    &quot;episodeNumber&quot;: 1,
        ///    &quot;title&quot;: &quot;Stewie Griffin: The Untold Story (Feature Movie)&quot;,
        ///    &quot;airDate&quot;: &quot;2006-05-21&quot;,
        ///    &quot;airDateUtc&quot;: &quot;2006-05-22T01:00:00Z&quot;,
        ///    &quot;overview&quot;: &quot;When Stewie sees a man who looks just like him on TV, he&apos;s convinced that he must be his real father. Stewie sets off on a cross-country road trip to find him, but his incredible journey leads to outrageous discoveries.&quot;,
        ///    &quot;hasFile&quot;: false,
        ///    &quot;mon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sonarr_Episode {
            get {
                return ResourceManager.GetString("Sonarr_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;EpisodeSearch&quot;,
        ///  &quot;body&quot;: {
        ///    &quot;episodeIds&quot;: [
        ///      1
        ///    ],
        ///    &quot;sendUpdatesToClient&quot;: true,
        ///    &quot;updateScheduledTask&quot;: true,
        ///    &quot;completionMessage&quot;: &quot;Completed&quot;,
        ///    &quot;name&quot;: &quot;EpisodeSearch&quot;,
        ///    &quot;trigger&quot;: &quot;manual&quot;
        ///  },
        ///  &quot;priority&quot;: &quot;normal&quot;,
        ///  &quot;status&quot;: &quot;queued&quot;,
        ///  &quot;queued&quot;: &quot;0001-01-01T00:00:00Z&quot;,
        ///  &quot;trigger&quot;: &quot;manual&quot;,
        ///  &quot;state&quot;: &quot;queued&quot;,
        ///  &quot;manual&quot;: true,
        ///  &quot;startedOn&quot;: &quot;0001-01-01T00:00:00Z&quot;,
        ///  &quot;sendUpdatesToClient&quot;: true,
        ///  &quot;updateScheduledTask&quot;: true,
        ///  &quot;id&quot;: 551827
        ///}.
        /// </summary>
        public static string Sonarr_EpisodeSearch {
            get {
                return ResourceManager.GetString("Sonarr_EpisodeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;title&quot;: &quot;Family Guy&quot;,
        ///    &quot;alternateTitles&quot;: [],
        ///    &quot;sortTitle&quot;: &quot;family guy&quot;,
        ///    &quot;seasonCount&quot;: 14,
        ///    &quot;totalEpisodeCount&quot;: 278,
        ///    &quot;episodeCount&quot;: 27,
        ///    &quot;episodeFileCount&quot;: 21,
        ///    &quot;sizeOnDisk&quot;: 7571641511,
        ///    &quot;status&quot;: &quot;continuing&quot;,
        ///    &quot;overview&quot;: &quot;Sick, twisted, politically incorrect and Freakin&apos; Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sonarr_Series {
            get {
                return ResourceManager.GetString("Sonarr_Series", resourceCulture);
            }
        }
    }
}
