//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZBDash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NZBDash.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Applications_CouchPotato_Movies {
            get {
                return ResourceManager.GetString("Applications_CouchPotato_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Applications_CouchPotato_Title {
            get {
                return ResourceManager.GetString("Applications_CouchPotato_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to see here!.
        /// </summary>
        public static string Applications_NzbGet_Download_NothingToSee {
            get {
                return ResourceManager.GetString("Applications_NzbGet_Download_NothingToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Applications_NzbGet_Tab_History {
            get {
                return ResourceManager.GetString("Applications_NzbGet_Tab_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Applications_NzbGet_Tab_Home {
            get {
                return ResourceManager.GetString("Applications_NzbGet_Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Applications_NzbGet_Tab_Logs {
            get {
                return ResourceManager.GetString("Applications_NzbGet_Tab_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NzbGet.
        /// </summary>
        public static string Applications_NzbGet_Title {
            get {
                return ResourceManager.GetString("Applications_NzbGet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Applications_SabNzbd_Tab_History {
            get {
                return ResourceManager.GetString("Applications_SabNzbd_Tab_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Applications_SabNzbd_Tab_Home {
            get {
                return ResourceManager.GetString("Applications_SabNzbd_Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SabNzbd.
        /// </summary>
        public static string Applications_SabNzbd_Title {
            get {
                return ResourceManager.GetString("Applications_SabNzbd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string Applications_Sonarr_Tab_TvShows {
            get {
                return ResourceManager.GetString("Applications_Sonarr_Tab_TvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonarr.
        /// </summary>
        public static string Applications_Sonarr_Title {
            get {
                return ResourceManager.GetString("Applications_Sonarr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Check the logs! :(.
        /// </summary>
        public static string Common_Error_Description {
            get {
                return ResourceManager.GetString("Common_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key.
        /// </summary>
        public static string Settings_ApiKey {
            get {
                return ResourceManager.GetString("Settings_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchPotato Settings.
        /// </summary>
        public static string Settings_CouchPotato_Title {
            get {
                return ResourceManager.GetString("Settings_CouchPotato_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Settings_Enabled {
            get {
                return ResourceManager.GetString("Settings_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address/Host name.
        /// </summary>
        public static string Settings_IpAddress {
            get {
                return ResourceManager.GetString("Settings_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your settings for Couch Potato.
        /// </summary>
        public static string Settings_Missing_Cp {
            get {
                return ResourceManager.GetString("Settings_Missing_Cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your settings for Kodi.
        /// </summary>
        public static string Settings_Missing_Kodi {
            get {
                return ResourceManager.GetString("Settings_Missing_Kodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your settings for NzbGet.
        /// </summary>
        public static string Settings_Missing_NzbGet {
            get {
                return ResourceManager.GetString("Settings_Missing_NzbGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your settings for Plex.
        /// </summary>
        public static string Settings_Missing_Plex {
            get {
                return ResourceManager.GetString("Settings_Missing_Plex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your settings for SabNzbd.
        /// </summary>
        public static string Settings_Missing_SabNzb {
            get {
                return ResourceManager.GetString("Settings_Missing_SabNzb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure your settings for Sonarr.
        /// </summary>
        public static string Settings_Missing_Sonarr {
            get {
                return ResourceManager.GetString("Settings_Missing_Sonarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Authentication.
        /// </summary>
        public static string Settings_NzbDash_Authenticate {
            get {
                return ResourceManager.GetString("Settings_NzbDash_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZBDash Settings.
        /// </summary>
        public static string Settings_NzbDash_Title {
            get {
                return ResourceManager.GetString("Settings_NzbDash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NzbGet Settings.
        /// </summary>
        public static string Settings_NzbGet_Title {
            get {
                return ResourceManager.GetString("Settings_NzbGet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plex Settings.
        /// </summary>
        public static string Settings_Plex_Title {
            get {
                return ResourceManager.GetString("Settings_Plex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_Port {
            get {
                return ResourceManager.GetString("Settings_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SabNzbd Settings.
        /// </summary>
        public static string Settings_SabNzb_Title {
            get {
                return ResourceManager.GetString("Settings_SabNzb_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on dashboard.
        /// </summary>
        public static string Settings_ShowOnDashboard {
            get {
                return ResourceManager.GetString("Settings_ShowOnDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonarr Settings.
        /// </summary>
        public static string Settings_Sonarr_Title {
            get {
                return ResourceManager.GetString("Settings_Sonarr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_Username {
            get {
                return ResourceManager.GetString("Settings_Username", resourceCulture);
            }
        }
    }
}
